<?php

namespace Database\Seeders;

use App\Enums\AdPlacement;
use App\Models\AdPlacementConfig;
use Illuminate\Database\Seeder;

class AdPlacementConfigSeeder extends Seeder
{
    public function run(): void
    {
        $zones = [
            // ── Web — full-width / structural ────────────────────────────────
            [
                'placement_key' => AdPlacement::WebTopBanner->value,
                'label' => AdPlacement::WebTopBanner->label(),
                'description' => 'Full-width banner directly below the site header. Highest visibility on all app pages.',
                'device_type' => 'desktop',
                'allowed_formats' => ['image', 'html', 'google_adsense'],
                'dimensions_width' => 728,
                'dimensions_height' => 90,
                'is_enabled' => true,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 10,
                'max_ads_per_page' => 1,
                'notes' => 'Rendered in (app)/layout.tsx above main content. Free users only.',
            ],
            // ── Web — sidebar ─────────────────────────────────────────────────
            [
                'placement_key' => AdPlacement::WebSidebarTop->value,
                'label' => AdPlacement::WebSidebarTop->label(),
                'description' => 'Square/rectangle at the top of the left sidebar, visible on all pages with the sidebar expanded.',
                'device_type' => 'desktop',
                'allowed_formats' => ['image', 'html', 'google_adsense'],
                'dimensions_width' => 300,
                'dimensions_height' => 250,
                'is_enabled' => true,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 10,
                'max_ads_per_page' => 1,
                'notes' => 'In sidebar.tsx, above the navigation list.',
            ],
            [
                'placement_key' => AdPlacement::WebSidebarBottom->value,
                'label' => AdPlacement::WebSidebarBottom->label(),
                'description' => 'Square at the bottom of the left sidebar, below navigation items.',
                'device_type' => 'desktop',
                'allowed_formats' => ['image', 'html', 'google_adsense'],
                'dimensions_width' => 300,
                'dimensions_height' => 250,
                'is_enabled' => false,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 10,
                'max_ads_per_page' => 1,
                'notes' => 'In sidebar.tsx, below the navigation list. Disabled by default — enable when sidebar is redesigned.',
            ],
            // ── Web — in-feed ─────────────────────────────────────────────────
            [
                'placement_key' => AdPlacement::WebInFeed1->value,
                'label' => AdPlacement::WebInFeed1->label(),
                'description' => 'Native/image card injected after the 3rd content card in the home and browse feeds.',
                'device_type' => 'desktop',
                'allowed_formats' => ['image', 'native', 'google_adsense'],
                'dimensions_width' => null,
                'dimensions_height' => null,
                'is_enabled' => true,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 8,
                'max_ads_per_page' => 1,
                'notes' => 'Inject at index 3 of the feed card array on home and browse pages.',
            ],
            [
                'placement_key' => AdPlacement::WebInFeed2->value,
                'label' => AdPlacement::WebInFeed2->label(),
                'description' => 'Native/image card injected after the 8th content card in the home and browse feeds.',
                'device_type' => 'desktop',
                'allowed_formats' => ['image', 'native', 'google_adsense'],
                'dimensions_width' => null,
                'dimensions_height' => null,
                'is_enabled' => true,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 8,
                'max_ads_per_page' => 1,
                'notes' => 'Inject at index 8 of the feed card array on home and browse pages.',
            ],
            // ── Web — player area ─────────────────────────────────────────────
            [
                'placement_key' => AdPlacement::WebPlayerAbove->value,
                'label' => AdPlacement::WebPlayerAbove->label(),
                'description' => 'Thin banner strip directly above the persistent player bar at the bottom of the screen.',
                'device_type' => 'desktop',
                'allowed_formats' => ['image', 'html'],
                'dimensions_width' => 728,
                'dimensions_height' => 50,
                'is_enabled' => false,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 20,
                'max_ads_per_page' => 1,
                'notes' => 'Sits between main content and the fixed player bar in (app)/layout.tsx. Enable once player layout supports it.',
            ],
            [
                'placement_key' => AdPlacement::WebBetweenSongs->value,
                'label' => AdPlacement::WebBetweenSongs->label(),
                'description' => 'Full-screen audio overlay that plays every 4 songs for free-tier users. Handled by AudioAdManager.',
                'device_type' => 'desktop',
                'allowed_formats' => ['audio'],
                'dimensions_width' => null,
                'dimensions_height' => null,
                'is_enabled' => true,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 15,
                'max_ads_per_page' => 1,
                'notes' => 'AudioAdManager.tsx intercepts playback. SONGS_BETWEEN_ADS constant controls frequency.',
            ],
            // ── Web — detail pages ────────────────────────────────────────────
            [
                'placement_key' => AdPlacement::WebSongPage->value,
                'label' => AdPlacement::WebSongPage->label(),
                'description' => 'Rectangle ad below the song metadata on the song detail page.',
                'device_type' => 'desktop',
                'allowed_formats' => ['image', 'html', 'native', 'google_adsense'],
                'dimensions_width' => 300,
                'dimensions_height' => 250,
                'is_enabled' => true,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 6,
                'max_ads_per_page' => 1,
                'notes' => 'Place in /songs/[slug]/page.tsx below the song info block.',
            ],
            [
                'placement_key' => AdPlacement::WebArtistPage->value,
                'label' => AdPlacement::WebArtistPage->label(),
                'description' => 'Rectangle ad in the sidebar or below the artist bio on the artist profile page.',
                'device_type' => 'desktop',
                'allowed_formats' => ['image', 'html', 'native', 'google_adsense'],
                'dimensions_width' => 300,
                'dimensions_height' => 250,
                'is_enabled' => true,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 6,
                'max_ads_per_page' => 1,
                'notes' => 'Place in /artists/[slug]/page.tsx.',
            ],
            [
                'placement_key' => AdPlacement::WebSearchInline->value,
                'label' => AdPlacement::WebSearchInline->label(),
                'description' => 'Native ad card injected among search results, clearly labelled "Sponsored".',
                'device_type' => 'desktop',
                'allowed_formats' => ['native', 'image'],
                'dimensions_width' => null,
                'dimensions_height' => null,
                'is_enabled' => false,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 5,
                'max_ads_per_page' => 1,
                'notes' => 'Inject at position 3 in search results list. Enable when search UX is finalized.',
            ],
            // ── Mobile — tab banners ──────────────────────────────────────────
            [
                'placement_key' => AdPlacement::MobileHomeBanner->value,
                'label' => AdPlacement::MobileHomeBanner->label(),
                'description' => 'Banner at the top of the Home tab, below the tab header.',
                'device_type' => 'mobile',
                'allowed_formats' => ['image', 'html'],
                'dimensions_width' => 320,
                'dimensions_height' => 50,
                'is_enabled' => true,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 10,
                'max_ads_per_page' => 1,
                'notes' => 'Top of (tabs)/index.tsx in the mobile app.',
            ],
            [
                'placement_key' => AdPlacement::MobileHomeInFeed->value,
                'label' => AdPlacement::MobileHomeInFeed->label(),
                'description' => 'Native card injected after the 3rd card in the Home tab content feed.',
                'device_type' => 'mobile',
                'allowed_formats' => ['image', 'native'],
                'dimensions_width' => null,
                'dimensions_height' => null,
                'is_enabled' => true,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 8,
                'max_ads_per_page' => 1,
                'notes' => 'Inject at index 3 of the FlatList data in (tabs)/index.tsx.',
            ],
            [
                'placement_key' => AdPlacement::MobileSearchBanner->value,
                'label' => AdPlacement::MobileSearchBanner->label(),
                'description' => 'Banner at the top of the Search tab, below the search input.',
                'device_type' => 'mobile',
                'allowed_formats' => ['image'],
                'dimensions_width' => 320,
                'dimensions_height' => 50,
                'is_enabled' => false,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 10,
                'max_ads_per_page' => 1,
                'notes' => 'Below the search bar in (tabs)/search.tsx. Enable when search UI is stable.',
            ],
            [
                'placement_key' => AdPlacement::MobileLibraryBanner->value,
                'label' => AdPlacement::MobileLibraryBanner->label(),
                'description' => 'Banner at the top of the Library tab.',
                'device_type' => 'mobile',
                'allowed_formats' => ['image'],
                'dimensions_width' => 320,
                'dimensions_height' => 50,
                'is_enabled' => false,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 8,
                'max_ads_per_page' => 1,
                'notes' => 'Top of (tabs)/library.tsx.',
            ],
            // ── Mobile — player area ──────────────────────────────────────────
            [
                'placement_key' => AdPlacement::MobilePlayerAbove->value,
                'label' => AdPlacement::MobilePlayerAbove->label(),
                'description' => 'Thin banner directly above the persistent mini-player bar at the bottom of all tab screens.',
                'device_type' => 'mobile',
                'allowed_formats' => ['image'],
                'dimensions_width' => 320,
                'dimensions_height' => 50,
                'is_enabled' => false,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 20,
                'max_ads_per_page' => 1,
                'notes' => 'Sits above the mini-player in global-mobile-chrome.tsx. Enable once mini-player layout supports it.',
            ],
            [
                'placement_key' => AdPlacement::MobileBetweenSongs->value,
                'label' => AdPlacement::MobileBetweenSongs->label(),
                'description' => 'Audio overlay ad that plays between tracks on mobile, same logic as the web AudioAdManager.',
                'device_type' => 'mobile',
                'allowed_formats' => ['audio'],
                'dimensions_width' => null,
                'dimensions_height' => null,
                'is_enabled' => false,
                'target_tiers' => ['free'],
                'frequency_cap_per_day' => 15,
                'max_ads_per_page' => 1,
                'notes' => 'Requires MobileAudioAdManager component (Phase 5e). Disabled until implemented.',
            ],
        ];

        foreach ($zones as $zone) {
            AdPlacementConfig::updateOrCreate(
                ['placement_key' => $zone['placement_key']],
                $zone
            );
        }
    }
}
