<?php

namespace Database\Seeders;

use App\Models\SubscriptionPlan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SubscriptionPlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Free',
                'slug' => 'free',
                'description' => 'Basic access — stream, discover and support artists at no cost.',
                'tier' => 'free',
                'type' => 'standard',
                'price' => 0,
                'price_monthly' => 0,
                'price_yearly' => 0,
                'price_local' => 0,
                'price_usd' => 0,
                'currency' => 'UGX',
                'interval' => 'month',
                'interval_count' => 1,
                'trial_days' => 0,
                'duration_days' => 30,
                'region' => 'EA',
                'features' => [
                    'Stream music with ads',
                    '3 downloads per day (128 kbps)',
                    'Basic discovery',
                    'Follow artists',
                ],
                'limits' => [
                    'max_downloads_per_day' => 3,
                    'max_audio_quality_kbps' => 128,
                    'max_uploads_per_month' => 0,
                ],
                'downloads_per_day' => 3,
                'max_downloads_per_day' => 3,
                'max_audio_quality_kbps' => 128,
                'streaming_quality' => '128',
                'has_ads' => true,
                'offline_mode' => false,
                'allows_offline' => false,
                'ad_free' => false,
                'is_active' => true,
                'is_visible' => true,
                'is_featured' => false,
                'is_trial' => false,
                'is_popular' => false,
                'sort_order' => 0,
            ],
            [
                'name' => 'Premium',
                'slug' => 'premium',
                'description' => 'Ad-free listening, high-quality audio and unlimited downloads.',
                'tier' => 'premium',
                'type' => 'standard',
                'price' => 15000,
                'price_monthly' => 15000,
                'price_yearly' => 150000,
                'price_local' => 15000,
                'price_usd' => 3.99,
                'currency' => 'UGX',
                'interval' => 'month',
                'interval_count' => 1,
                'trial_days' => 7,
                'duration_days' => 30,
                'region' => 'EA',
                'features' => [
                    'Ad-free streaming',
                    'Unlimited downloads (320 kbps)',
                    'Offline listening',
                    'High-quality audio',
                    'Priority support',
                ],
                'limits' => [
                    'max_downloads_per_day' => -1,
                    'max_audio_quality_kbps' => 320,
                    'max_uploads_per_month' => 0,
                ],
                'downloads_per_day' => null,
                'max_downloads_per_day' => null,
                'max_audio_quality_kbps' => 320,
                'streaming_quality' => '320',
                'has_ads' => false,
                'offline_mode' => true,
                'allows_offline' => true,
                'ad_free' => true,
                'is_active' => true,
                'is_visible' => true,
                'is_featured' => true,
                'is_trial' => false,
                'is_popular' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Artist',
                'slug' => 'artist',
                'description' => 'Upload, monetize and grow your music career with analytics and distribution.',
                'tier' => 'artist',
                'type' => 'creator',
                'price' => 25000,
                'price_monthly' => 25000,
                'price_yearly' => 250000,
                'price_local' => 25000,
                'price_usd' => 6.99,
                'currency' => 'UGX',
                'interval' => 'month',
                'interval_count' => 1,
                'trial_days' => 14,
                'duration_days' => 30,
                'region' => 'EA',
                'features' => [
                    'Everything in Premium',
                    'Upload up to 50 songs/month',
                    'Artist analytics dashboard',
                    'Fan engagement tools',
                    'Revenue tracking & payouts',
                    'Priority playlist placement',
                ],
                'limits' => [
                    'max_downloads_per_day' => -1,
                    'max_audio_quality_kbps' => 320,
                    'max_uploads_per_month' => 50,
                ],
                'downloads_per_day' => null,
                'max_downloads_per_day' => null,
                'max_uploads_per_month' => 50,
                'max_audio_quality_kbps' => 320,
                'streaming_quality' => '320',
                'has_ads' => false,
                'offline_mode' => true,
                'allows_offline' => true,
                'ad_free' => true,
                'is_active' => true,
                'is_visible' => true,
                'is_featured' => false,
                'is_trial' => false,
                'is_popular' => false,
                'sort_order' => 2,
            ],
            [
                'name' => 'Label',
                'slug' => 'label',
                'description' => 'Manage multiple artists, advanced analytics and bulk distribution.',
                'tier' => 'label',
                'type' => 'creator',
                'price' => 100000,
                'price_monthly' => 100000,
                'price_yearly' => 1000000,
                'price_local' => 100000,
                'price_usd' => 26.99,
                'currency' => 'UGX',
                'interval' => 'month',
                'interval_count' => 1,
                'trial_days' => 14,
                'duration_days' => 30,
                'region' => 'EA',
                'features' => [
                    'Everything in Artist',
                    'Manage unlimited artists',
                    'Bulk upload & distribution',
                    'Advanced analytics & reports',
                    'Custom branding',
                    'Dedicated account manager',
                    'API access',
                ],
                'limits' => [
                    'max_downloads_per_day' => -1,
                    'max_audio_quality_kbps' => 320,
                    'max_uploads_per_month' => 500,
                ],
                'downloads_per_day' => null,
                'max_downloads_per_day' => null,
                'max_uploads_per_month' => 500,
                'max_audio_quality_kbps' => 320,
                'streaming_quality' => '320',
                'has_ads' => false,
                'offline_mode' => true,
                'allows_offline' => true,
                'ad_free' => true,
                'is_active' => true,
                'is_visible' => true,
                'is_featured' => false,
                'is_trial' => false,
                'is_popular' => false,
                'sort_order' => 3,
            ],
        ];

        foreach ($plans as $plan) {
            SubscriptionPlan::updateOrCreate(
                ['slug' => $plan['slug']],
                array_merge($plan, ['uuid' => Str::uuid()->toString()])
            );
        }
    }
}
