<?php

namespace Database\Seeders;

use App\Models\SubscriptionPlan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SubscriptionPlanSeeder extends Seeder
{
    public function run(): void
    {
        $free = [
            'streaming.ad_free' => false,
            'streaming.audio_quality_kbps' => 128,
            'streaming.offline' => false,
            'streaming.offline_devices' => 0,
            'streaming.downloads_per_day' => 3,
            'streaming.collaborative_playlists' => false,
            'streaming.cross_device_resume' => true,
            'streaming.early_release_access' => false,
            'rewards.credit_multiplier' => 1,
            'rewards.monthly_credit_bonus' => 0,
            'rewards.subscriber_giveaways' => false,
            'fans.club_access_level' => 'basic',
            'fans.event_presale_hours' => 0,
            'fans.ticket_fee_discount_percent' => 0,
            'fans.store_fee_discount_percent' => 0,
            'creator.artist_profiles' => 0,
            'creator.uploads_per_month' => 0,
            'creator.podcasts' => 0,
            'creator.podcast_episodes_per_month' => 0,
            'creator.analytics_level' => 'none',
            'creator.royalty_split_collaborators' => 0,
            'creator.scheduled_releases' => false,
            'creator.monetization' => false,
            'creator.fan_tips' => false,
            'creator.global_distribution' => false,
            'creator.distribution_releases_per_year' => 0,
            'creator.isrc_upc_assistance' => false,
            'creator.fan_club_management' => false,
            'creator.crowdfunding' => false,
            'finance.withdrawal_minimum_ugx' => 25000,
            'finance.withdrawal_fee_percent' => 2.5,
            'finance.withdrawals_per_month' => 1,
            'finance.payout_priority' => 'standard',
            'finance.statement_frequency' => 'monthly',
            'finance.sacco_automation' => false,
            'promotions.active_campaigns' => 0,
            'promotions.analytics_level' => 'none',
            'promotions.platform_commission_percent' => 10,
            'events.active_events' => 0,
            'events.ticket_types_per_event' => 0,
            'events.discount_codes' => false,
            'events.waitlists' => false,
            'events.staff_seats' => 0,
            'events.attendee_exports' => false,
            'events.analytics_level' => 'none',
            'events.platform_commission_percent' => 8,
            'events.processing_fee_percent' => 2.9,
            'store.shops' => 0,
            'store.products_per_shop' => 0,
            'store.promotions' => false,
            'store.analytics_level' => 'none',
            'store.staff_seats' => 0,
            'store.platform_commission_percent' => 8,
            'store.minimum_platform_fee_ugx' => 1000,
            'organization.managed_artists' => 0,
            'organization.team_seats' => 1,
            'organization.role_permissions' => false,
            'organization.bulk_operations' => false,
            'organization.custom_branding' => false,
            'organization.api_access' => false,
            'organization.webhooks' => false,
            'organization.audit_logs' => false,
            'support.level' => 'community',
            'support.priority_content_review' => false,
            'security.device_management' => false,
            'reports.csv_exports' => false,
            'reports.scheduled_delivery' => false,
            'reports.custom_branding' => false,
        ];

        $emong = array_merge($free, [
            'streaming.ad_free' => true,
            'streaming.audio_quality_kbps' => 320,
            'streaming.offline' => true,
            'streaming.offline_devices' => 1,
            'streaming.downloads_per_day' => 25,
            'streaming.collaborative_playlists' => true,
            'streaming.early_release_access' => true,
            'rewards.credit_multiplier' => 1.1,
            'rewards.monthly_credit_bonus' => 100,
            'rewards.subscriber_giveaways' => true,
            'fans.event_presale_hours' => 12,
            'fans.ticket_fee_discount_percent' => 2,
            'fans.store_fee_discount_percent' => 2,
            'creator.artist_profiles' => 1,
            'creator.uploads_per_month' => 10,
            'creator.podcasts' => 1,
            'creator.podcast_episodes_per_month' => 10,
            'creator.analytics_level' => 'basic',
            'creator.royalty_split_collaborators' => 3,
            'creator.scheduled_releases' => true,
            'creator.monetization' => true,
            'creator.fan_tips' => true,
            'finance.withdrawal_minimum_ugx' => 25000,
            'finance.withdrawals_per_month' => 2,
            'promotions.active_campaigns' => 1,
            'promotions.analytics_level' => 'basic',
            'promotions.platform_commission_percent' => 9,
            'events.active_events' => 1,
            'events.ticket_types_per_event' => 3,
            'events.staff_seats' => 1,
            'events.analytics_level' => 'basic',
            'events.platform_commission_percent' => 7,
            'events.processing_fee_percent' => 2.5,
            'store.shops' => 1,
            'store.products_per_shop' => 25,
            'store.analytics_level' => 'basic',
            'store.platform_commission_percent' => 7,
            'store.minimum_platform_fee_ugx' => 500,
            'organization.managed_artists' => 1,
        ]);

        $eris = array_merge($emong, [
            'streaming.offline_devices' => 3,
            'streaming.downloads_per_day' => 100,
            'rewards.credit_multiplier' => 1.25,
            'rewards.monthly_credit_bonus' => 300,
            'fans.club_access_level' => 'premium',
            'fans.event_presale_hours' => 24,
            'fans.ticket_fee_discount_percent' => 5,
            'fans.store_fee_discount_percent' => 5,
            'creator.artist_profiles' => 5,
            'creator.uploads_per_month' => 50,
            'creator.podcasts' => 5,
            'creator.podcast_episodes_per_month' => 50,
            'creator.analytics_level' => 'advanced',
            'creator.royalty_split_collaborators' => 10,
            'creator.global_distribution' => true,
            'creator.distribution_releases_per_year' => 24,
            'creator.isrc_upc_assistance' => true,
            'creator.fan_club_management' => true,
            'creator.crowdfunding' => true,
            'finance.withdrawal_minimum_ugx' => 10000,
            'finance.withdrawal_fee_percent' => 1.5,
            'finance.withdrawals_per_month' => 4,
            'finance.payout_priority' => 'fast',
            'finance.statement_frequency' => 'weekly',
            'finance.sacco_automation' => true,
            'promotions.active_campaigns' => 10,
            'promotions.analytics_level' => 'advanced',
            'promotions.platform_commission_percent' => 7,
            'events.active_events' => 10,
            'events.ticket_types_per_event' => 10,
            'events.discount_codes' => true,
            'events.waitlists' => true,
            'events.staff_seats' => 5,
            'events.attendee_exports' => true,
            'events.analytics_level' => 'advanced',
            'events.platform_commission_percent' => 6,
            'events.processing_fee_percent' => 2,
            'store.products_per_shop' => 250,
            'store.promotions' => true,
            'store.analytics_level' => 'advanced',
            'store.staff_seats' => 3,
            'store.platform_commission_percent' => 6,
            'store.minimum_platform_fee_ugx' => 250,
            'organization.managed_artists' => 5,
            'organization.team_seats' => 3,
            'organization.role_permissions' => true,
            'support.level' => 'priority',
            'support.priority_content_review' => true,
            'reports.csv_exports' => true,
        ]);

        $engatuny = array_merge($eris, [
            'streaming.offline_devices' => 5,
            'streaming.downloads_per_day' => -1,
            'rewards.credit_multiplier' => 1.5,
            'rewards.monthly_credit_bonus' => 1000,
            'fans.club_access_level' => 'vip',
            'fans.event_presale_hours' => 48,
            'fans.ticket_fee_discount_percent' => 10,
            'fans.store_fee_discount_percent' => 10,
            'creator.artist_profiles' => 50,
            'creator.uploads_per_month' => 500,
            'creator.podcasts' => -1,
            'creator.podcast_episodes_per_month' => -1,
            'creator.analytics_level' => 'organization',
            'creator.royalty_split_collaborators' => -1,
            'creator.distribution_releases_per_year' => -1,
            'finance.withdrawal_minimum_ugx' => 5000,
            'finance.withdrawal_fee_percent' => 0.5,
            'finance.withdrawals_per_month' => -1,
            'finance.payout_priority' => 'priority',
            'finance.statement_frequency' => 'on_demand',
            'promotions.active_campaigns' => -1,
            'promotions.analytics_level' => 'agency',
            'promotions.platform_commission_percent' => 5,
            'events.active_events' => -1,
            'events.ticket_types_per_event' => -1,
            'events.staff_seats' => -1,
            'events.analytics_level' => 'organization',
            'events.platform_commission_percent' => 4,
            'events.processing_fee_percent' => 1.5,
            'store.shops' => -1,
            'store.products_per_shop' => -1,
            'store.analytics_level' => 'organization',
            'store.staff_seats' => -1,
            'store.platform_commission_percent' => 4,
            'store.minimum_platform_fee_ugx' => 0,
            'organization.managed_artists' => 50,
            'organization.team_seats' => 10,
            'organization.bulk_operations' => true,
            'organization.custom_branding' => true,
            'organization.api_access' => true,
            'organization.webhooks' => true,
            'organization.audit_logs' => true,
            'support.level' => 'dedicated',
            'security.device_management' => true,
            'reports.scheduled_delivery' => true,
            'reports.custom_branding' => true,
        ]);

        $plans = [
            $this->plan('Free', 'free', 'Free access to listen, discover, participate and transact.', 'free', 'standard', 0, 0, ['Stream music with ads', '3 downloads per day', 'Follow artists and build playlists', 'Earn credits and join the community'], $free, 3, 0, 128, true, false, 0, false),
            $this->plan('Emong', 'emong', 'A gentle first step into better listening and essential creator tools.', 'emong', 'personal', 3000, 30000, ['Ad-free 320 kbps listening', 'Offline listening and 25 daily downloads', '10 creator uploads every month', 'Basic analytics, tips and monetization', 'One event, promotion and store workspace', 'Two wallet withdrawals per month'], $emong, 25, 10, 320, false, true, 1, false),
            $this->plan('Eris', 'eris', 'Professional tools for working artists, promoters, organizers and sellers.', 'eris', 'professional', 5000, 50000, ['Everything in Emong', '50 uploads and advanced analytics', 'Global distribution and royalty splits', 'Fan clubs and crowdfunding', 'Expanded events, promotions and store tools', 'Lower withdrawal minimum and commissions'], $eris, 100, 50, 320, false, true, 2, true),
            $this->plan('Engatuny', 'engatuny', 'Organization-scale control for labels, studios, agencies and event businesses.', 'engatuny', 'organization', 15000, 150000, ['Everything in Eris', 'Bulk catalogue and distribution operations', 'Manage up to 50 artists', 'Organization analytics and branded reports', 'API, webhooks, audit logs and team permissions', 'Lowest withdrawal minimum and platform commissions'], $engatuny, null, 500, 320, false, true, 3, false),
        ];

        foreach ($plans as $plan) {
            // Deploys may run this seeder repeatedly. Only bootstrap missing
            // plans so prices, limits and entitlements edited in Admin remain
            // the source of truth after the first production release.
            SubscriptionPlan::firstOrCreate(
                ['slug' => $plan['slug']],
                array_merge($plan, ['uuid' => (string) Str::uuid()])
            );
        }

        SubscriptionPlan::whereIn('slug', ['premium', 'artist', 'label'])
            ->update(['is_active' => false, 'is_visible' => false]);
    }

    private function plan(string $name, string $slug, string $description, string $tier, string $type, int $monthly, int $yearly, array $features, array $entitlements, ?int $downloads, int $uploads, int $quality, bool $hasAds, bool $offline, int $sortOrder, bool $popular): array
    {
        return [
            'name' => $name,
            'slug' => $slug,
            'description' => $description,
            'tier' => $tier,
            'type' => $type,
            'price' => $monthly,
            'price_monthly' => $monthly,
            'price_yearly' => $yearly,
            'price_local' => $monthly,
            'price_usd' => 0,
            'currency' => 'UGX',
            'interval' => 'month',
            'interval_count' => 1,
            'trial_days' => $monthly > 0 ? 7 : 0,
            'duration_days' => 30,
            'region' => 'EA',
            'features' => $features,
            'entitlements' => $entitlements,
            'limits' => ['max_downloads_per_day' => $downloads, 'max_audio_quality_kbps' => $quality, 'max_uploads_per_month' => $uploads],
            'downloads_per_day' => $downloads,
            'max_downloads_per_day' => $downloads,
            'max_uploads_per_month' => $uploads,
            'max_audio_quality_kbps' => $quality,
            'streaming_quality' => (string) $quality,
            'has_ads' => $hasAds,
            'offline_mode' => $offline,
            'allows_offline' => $offline,
            'ad_free' => ! $hasAds,
            'is_active' => true,
            'is_visible' => true,
            'is_featured' => $popular,
            'is_trial' => false,
            'is_popular' => $popular,
            'sort_order' => $sortOrder,
        ];
    }
}
